# Call this whatever
name: scrape

# When does it run?
on:

# I can click a button and forcd it to run
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Download all code from repo
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # make sure filename matches the filename here
      - name: Run the scraping script
        run: python scraper.py
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
